// Auto-generated from x86 System Test Report Template v0006.xlsm
// Do NOT edit manually unless you know what you're doing.

export default [
  {
    "category": "HW",
    "code": "AVoIP_001",
    "testCase": "To confirm that display on monitor through AVoIP signals work well.",
    "testProcedure": "1 Transmitter (TX): Connect to the audio and video signal source (host).\n2 Receiver (RX): Connect to display device.\n3 Network cable: Connect the transmitter and receiver.\n4 Power on all devices:Ensure the transmitter, receiver, host, and display device are powered on.",
    "testCriteria": "All supported resolution can work well with monitor.",
    "result": "pending",
    "workHrs": 0.3,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "HW",
    "code": "AVoIP_002",
    "testCase": "To confirm that the hot plug of AVoIP works well.",
    "testProcedure": "1 Transmitter (TX): Connect to the audio and video signal source (host).\n2 Receiver (RX): Connect to display device.\n3 Network cable: Connect the transmitter and receiver.\n4 Power on all devices:Ensure the transmitter, receiver, host, and display device are powered on.\n5.Unplug Network cable and plug cable again 3 times.",
    "testCriteria": "Monitor always has display after plug of Network cable.",
    "result": "pending",
    "workHrs": 0.3,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "HW",
    "code": "AVoIP_003",
    "testCase": "To confirm that audio of  AVoIP monitor can function well.",
    "testProcedure": "1 Transmitter (TX): Connect to the audio and video signal source (host).\n2 Receiver (RX): Connect to display device.\n3 Network cable: Connect the transmitter and receiver.\n4 Power on all devices:Ensure the transmitter, receiver, host, and display device are powered on.\n5.Host: Play audio and video signal sources.",
    "testCriteria": "The sound of music should be output to monitor's audio.",
    "result": "pending",
    "workHrs": 0.3,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "HW",
    "code": "BUT_001",
    "testCase": "To confirm Button functionality.",
    "testProcedure": "",
    "testCriteria": "According to spec., all functionalities shoud be PASS with its definition.",
    "result": "pending",
    "workHrs": 0.2,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "HW",
    "code": "CPU_001",
    "testCase": "To confirm that CPU's information listed by software meet the product specification.",
    "testProcedure": "1. Boot system into Windows OS.\n2. Execute CPU-Z utility to check CPU information.",
    "testCriteria": "The information CPU-Z shows should meet CPU's specification and system requirement.",
    "result": "pending",
    "workHrs": 0.2,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "HW",
    "code": "GPIO_001",
    "testCase": "To confirm GPIO functionality.",
    "testProcedure": "1. Connect each GPO to GPI with a cable.\n2. Boot system to uEFI shell.\n3. Execute GPIO read/write utility to program GPO to specific high/low level.\n4. Read GPI state.",
    "testCriteria": "GPI state should be the same as GPO's level after programing.",
    "result": "pending",
    "workHrs": 0.3,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "HW",
    "code": "LED_001",
    "testCase": "To confirm that Power LED function.",
    "testProcedure": "1. Turn on power supply to offer power to system.\n2. Observe status of Power LED.",
    "testCriteria": "Power LED should be lighted after power is applied to system.",
    "result": "pending",
    "workHrs": 0.1,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "HW",
    "code": "MEM_001",
    "testCase": "To confirm that memory's frequency and capacity are well-recognized by system and functions well.",
    "testProcedure": "1. Power on system and boot into Windows OS.\n2. Execute HWINFO to check detected memory information like operating speed, capacity, memory type, etc.,\n3. Execute BurnInTest for 1 hour to check memory functionality.",
    "testCriteria": "1. The information gotten by software should meet memory and system specification.\n2. BurnInTest should not have error.",
    "result": "pending",
    "workHrs": 1.0,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "HW",
    "code": "NVMe_001",
    "testCase": "To confirm that NVMe work well through M.2 slot.",
    "testProcedure": "1. Install NVMe into M.2 slot (PCIe signal).\n2. Power on system to install Windows OS.",
    "testCriteria": "Operating system should be installed on NVMe without problem.",
    "result": "pending",
    "workHrs": 0.2,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "HW",
    "code": "NET_001",
    "testCase": "To confirm that all ethernet ports work as expectation.",
    "testProcedure": "1. Connect ethernet cable to all ethernet ports.\n2. Boot into Windows OS.\n3. Access web link through Ethernet or transfer big file between two Etherent ports.",
    "testCriteria": "Ethernet should be recognized well and function well.",
    "result": "pending",
    "workHrs": 0.2,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "HW",
    "code": "POE_001",
    "testCase": "To confirm that PD function work well with system.",
    "testProcedure": "1. Connect ethernet port with PD function to PSE.\n2. Power on system with power provided through Ethernet port.\n3. Configure system to work with heavy loading.",
    "testCriteria": "System should work well without problem.",
    "result": "pending",
    "workHrs": 0.2,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "HW",
    "code": "RTC_001",
    "testCase": "To confirm RTC timer is precise after 3 days AC off.",
    "testProcedure": "1. Boot DUT into operating system.\n2. Set time retrieved from internet time server by executing NTPClock utility.\n3. AC off for 3 days.\n4. After 3 days, check system time with time server to get the difference.",
    "testCriteria": "The difference between server and DUT SHOULD be less than ±2.0 sec/24 hours.",
    "result": "pending",
    "workHrs": 72.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "HW",
    "code": "RTC_002",
    "testCase": "To confirm RTC timer is precise after 1 day full running at HIGH Temperature.",
    "testProcedure": "1. Boot DUT into operating system and set chamber temperature to highest temperature listed in system specification.\n2. Set time retrieved from internet time server by executing NTPClock utility.\n3. Start BurnTest for 24 hours.\n4. After 24 hours, check system time with time server to get the difference.",
    "testCriteria": "The difference between server and DUT SHOULD be less than ±2.0 sec/24 hours.",
    "result": "pending",
    "workHrs": 24.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "HW",
    "code": "SSD_001",
    "testCase": "To confirm that SSD work well through SATA interface.",
    "testProcedure": "1. Install SSD into SATA port or M.2 slot (SATA signal).\n2. Power on system to install Windows OS.",
    "testCriteria": "Operating system should be installed on SSD without problem.",
    "result": "pending",
    "workHrs": 0.2,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "HW",
    "code": "SSD_002",
    "testCase": "To confirm RAID functionality.",
    "testProcedure": "1. After configuring two SATA SSDs with RAID function, reboot system.\n2. Install Windows OS.",
    "testCriteria": "Operating system should be installed on two SSDs without problem and RAID work well.",
    "result": "pending",
    "workHrs": 0.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "HW",
    "code": "SP_001",
    "testCase": "To verify serial ports' functionality.",
    "testProcedure": "1. Inserts serial port loopback into all serial ports.\n2. Boot system into Windows operating system.\n3. Execute BurnInTest and select serial port test.\n4. Configure baud rate from 9600 to 115200. Perform each baud rate testing 20 cycles.",
    "testCriteria": "All BurnInTest on serial ports with different baud rate should be PASS.",
    "result": "pending",
    "workHrs": 0.3,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "HW",
    "code": "SP_002",
    "testCase": "To confirm that RS422 mode works well with serial ports that support it.",
    "testProcedure": "1. Inserts specific RS422 serial port loopback into the port which supports RS422.\n2. Boot into BIOS setup utility and set serial port to be RS422 mode.\n3. Reboot to Windows OS.\n4. Execute BurnInTest and select serial port test.\n5. Configure baud rate to 115200, then perform test 10 cycles.",
    "testCriteria": "It should not have error during BurnInTest.",
    "result": "pending",
    "workHrs": 0.3,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "HW",
    "code": "SP_003",
    "testCase": "To confirm that RS485 mode works well with serial ports that support it.",
    "testProcedure": "1. Prepare a PC with serial port has RS485 supported. Name this PC as PC1.\n2. Connect system's RS485 signal data+ to data+ of PC1's RS485 and system's RS485 signal data- to data- of PC1's RS485.\n3. Boot system and PC1 to Windows OS and execute PuTTY/TTYSWIRL.\n4. Configure session to serial port of system and PC1.\n5. Set \"local echo\" and \"local line editing\" to \"Force on\" on PuTTY setting on both system and PC1.\n6. Set system as master and PC1 as slave. Type some words on PuTTY/TTYSWIRL terminal of master.\n7. Set PC1 as master and sytem as slave. Type some words on PuTTY/TTYSWIRL terminal of master.",
    "testCriteria": "Terminal of slave should respond what are typed on terminal of master.",
    "result": "pending",
    "workHrs": 0.3,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "HW",
    "code": "TPM_001",
    "testCase": "To confirm that BitLocker work well with TPM enabled system.",
    "testProcedure": "1. Boot system with TPM enabled.\n2. Turn on BitLocker in Microsoft Windows operating system on  bootable device step by step.\n3. Shutdown system and remove BitLocker set storage device to another system.\n4. Power on new system and boot into operating system.",
    "testCriteria": "During booting, it will ask for key-in key to boot operating system.",
    "result": "pending",
    "workHrs": 1.0,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "HW",
    "code": "USB_001",
    "testCase": "To confirm that all USB ports function well and meet product's specification.",
    "testProcedure": "1. Plug USB mouse/USB keyboard/USB disk/USB Hub into all USB ports.\n2. Boot system into Windows OS.\n3. Unplug and then plug USB device 10 times.\n4. Check USB operating speed.",
    "testCriteria": "1. USB device should work well with all USB ports.\n2. USB's operating performance should meet product's specification.",
    "result": "pending",
    "workHrs": 0.2,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "HW",
    "code": "WDT_001",
    "testCase": "To confirm watchdog timer's functionality.",
    "testProcedure": "1. Boot system into uEFI shell.\n2. Execute watchdog timer utility to enable watchdog timer and configure timeout value to 10 seconds.\n3. Reset timer counter every 5 seconds 3 times with 10 seconds timeout value.",
    "testCriteria": "System should not be reset caused by watchdog timer within 25 seconds and reset without resetting watchdog timer counter.",
    "result": "pending",
    "workHrs": 0.2,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "HW",
    "code": "WLS_001",
    "testCase": "To confirm that Wi-Fi module work well with installed antennae.",
    "testProcedure": "1. Install Wi-Fi module into slots and antennae.\n2. Connect Wi-Fi to wireless AP to get IP and link to FTP server.\n3. Download 1GB file and upload 1GB file to FTP server.",
    "testCriteria": "Wi-Fi connects to AP without problem and work well with file transfer.",
    "result": "pending",
    "workHrs": 0.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "Perf",
    "code": "3DMark_001",
    "testCase": "Measure performance of graphics card or onboard graphic.",
    "testProcedure": "In Windows operating system, execute 3D Mark benchmark test and capture the photo of score.",
    "testCriteria": "3DMark software SHOULD run well and can come out result for each testing items.",
    "result": "pending",
    "workHrs": 0.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "Perf",
    "code": "AIDA_001",
    "testCase": "Measure performance of disks.",
    "testProcedure": "In Windows operating system, execute AIDA64 test and capture the photo of score.",
    "testCriteria": "AIDA64 SHOULD run well and come out result for each testing items.",
    "result": "pending",
    "workHrs": 0.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "Perf",
    "code": "AIDA_002",
    "testCase": "Measure performance of Cache & Memory.",
    "testProcedure": "In Windows operating system, execute AIDA64 test and capture the photo of score.",
    "testCriteria": "AIDA64 SHOULD run well and come out result for each testing items.",
    "result": "pending",
    "workHrs": 0.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "Perf",
    "code": "CineB_001",
    "testCase": "Measure performance of CPU and onboard graphic.",
    "testProcedure": "In Windows operating system, execute CineBench test and capture the photo of score.",
    "testCriteria": "CineBench SHOULD run well and come out result for each testing items.",
    "result": "pending",
    "workHrs": 0.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "Perf",
    "code": "CDM_001",
    "testCase": "To get benchmark of read and write of storage device.",
    "testProcedure": "In Windows operating system, execute CrystalDiskMark and capture the photo of score.",
    "testCriteria": "CrystalDiskMark SHOULD run well and come out result for each testing items.",
    "result": "pending",
    "workHrs": 0.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "Perf",
    "code": "CDM_002",
    "testCase": "To get benchmark of read and write of USB 3.X device.",
    "testProcedure": "In Windows operating system, execute CrystalDiskMark and capture the photo of score.",
    "testCriteria": "CrystalDiskMark SHOULD run well and come out result for each testing items.",
    "result": "pending",
    "workHrs": 0.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "Perf",
    "code": "PASSM_002",
    "testCase": "Measure performance of sub-system of computer.",
    "testProcedure": "In Windows operating system, execute PerformanceTest and capture the photo of score.",
    "testCriteria": "PerformanceTest SHOULD run well and come out result for each testing items.",
    "result": "pending",
    "workHrs": 0.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "Reli",
    "code": "TAT_001",
    "testCase": "Stress testing under ambient temperature with system suppoted minimum voltage input.",
    "testProcedure": "1. Boot system into Windows OS.\n2. Execute BurnInTest on CPU (100%), Memory(90%) & Disk(90%) and Graphic related test item with 50% load.\n3. Execute HWINFO64 to log temperature of CPU, memory and Disk.\n4. Keep running BurnInTest 4 hour.\nNOTE: Store log file in the directory of saved test report.",
    "testCriteria": "1. System should not hang and has BSOD.\n2. Recorded average temperature of CPU is under 70°C.\n3. Recorded average temperature of Memory is under 65°C or under 75°C (WT Memory).\n4. Record average temperature of Disk is under 50°C or under 65°C (WT Disk).",
    "result": "pending",
    "workHrs": 4.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "Reli",
    "code": "TAT_002",
    "testCase": "Stress testing under ambient temperature with system suppoted maximum voltage input.",
    "testProcedure": "1. Boot system into Windows OS.\n2. Execute BurnInTest on CPU (100%), Memory(90%) & Disk(90%) and Graphic related test item with 50% load.\n3. Execute HWINFO64 to log temperature of CPU, memory and Disk.\n4. Keep running BurnInTest 4 hour.\nNOTE: Store log file in the directory of saved test report.",
    "testCriteria": "1. System should not hang and has BSOD.\n2. Recorded average temperature of CPU is under 70°C.\n3. Recorded average temperature of Memory is under 65°C or under 75°C (WT Memory).\n4. Record average temperature of Disk is under 50°C or under 65°C (WT Disk).",
    "result": "pending",
    "workHrs": 4.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "Reli",
    "code": "TAT_003",
    "testCase": "Stress testing under ambient temperature with specific required voltage input.",
    "testProcedure": "1. Boot system into Windows OS.\n2. Execute BurnInTest on CPU (100%), Memory(90%) & Disk(90%) and Graphic related test item with 50% load.\n3. Execute HWINFO64 to log temperature of CPU, memory and Disk.\n4. Keep running BurnInTest 4 hour.\nNOTE: Store log file in the directory of saved test report.",
    "testCriteria": "1. System should not hang and has BSOD.\n2. Recorded average temperature of CPU is under 70°C.\n3. Recorded average temperature of Memory is under 65°C or under 75°C (WT Memory).\n4. Record average temperature of Disk is under 50°C or under 65°C (WT Disk).",
    "result": "pending",
    "workHrs": 4.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "Reli",
    "code": "TST_001",
    "testCase": "Stress testing under system defined maximum operating temperature and humidity.",
    "testProcedure": "1. Boot system into Windows OS.\n2. Execute BurnInTest on CPU (100%), Memory(90%) & Disk(90%) and Graphic related test item with 50% load.\n3. Execute HWINFO64 to log temperature of CPU, memory and Disk.\n4. Keep running BurnInTest 4 hour.\nNOTE: Store log file in the directory of saved test report.",
    "testCriteria": "1. System should not hang and has BSOD.\n2. Recorded average temperature of CPU is under 95°C.\n3. Recorded average temperature of Memory is under 85°C or under 95°C (WT Memory).\n4. Record average temperature of Disk is under 70°C or under 85°C (WT Disk).",
    "result": "pending",
    "workHrs": 4.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "Reli",
    "code": "TST_002",
    "testCase": "Stress testing under system defined minimum operating temperature.",
    "testProcedure": "1. Boot system into Windows OS.\n2. Execute BurnInTest on CPU (100%), Memory(90%) & Disk(90%) and Graphic related test item with 50% load.\n3. Execute HWINFO64 to log temperature of CPU, memory and Disk.\n4. Keep running BurnInTest 4 hour.\nNOTE: Store log file in the directory of saved test report.",
    "testCriteria": "1. System should not hang and has BSOD.\n2. Recorded average temperature of CPU is under 95°C.\n3. Recorded average temperature of Memory is under 85°C or under 95°C (WT Memory).\n4. Record average temperature of Disk is under 70°C or under 85°C (WT Disk).",
    "result": "pending",
    "workHrs": 4.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "Reli",
    "code": "TST_003",
    "testCase": "Stress testing under specific required operating temperature and humidity.",
    "testProcedure": "1. Boot system into Windows OS.\n2. Execute BurnInTest on CPU (100%), Memory(90%) & Disk(90%) and Graphic related test item with 50% load.\n3. Execute HWINFO64 to log temperature of CPU, memory and Disk.\n4. Keep running BurnInTest 4 hour.\nNOTE: Store log file in the directory of saved test report.",
    "testCriteria": "1. System should not hang and has BSOD.\n2. Recorded average temperature of CPU is under 95°C.\n3. Recorded average temperature of Memory is under 85°C or under 95°C (WT Memory).\n4. Record average temperature of Disk is under 70°C or under 85°C (WT Disk).",
    "result": "pending",
    "workHrs": 4.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "Reli",
    "code": "TST_004",
    "testCase": "Stress testing under system required maximum operating temperature and humidity of AVoIP device.",
    "testProcedure": "1. Place the AVoIP device in the test chamber.\n2. Connect relevant peripheral systems.\n3. Start the Windows operating system.\n4. Test test should last at least 4 hours.",
    "testCriteria": "Device under test must operate normally, and its connection to related peripheral systems must be free of noise, flicker, distortion or any other anomalies.",
    "result": "pending",
    "workHrs": 4.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "Reli",
    "code": "TST_005",
    "testCase": "Stress testing under system required minimum operating temperature and humidity of AVoIP device.",
    "testProcedure": "1. Place the AVoIP device in the test chamber.\n2. Connect relevant peripheral systems.\n3. Start the Windows operating system.\n4. Test test should last at least 4 hours.",
    "testCriteria": "Device under test must operate normally, and its connection to related peripheral systems must be free of noise, flicker, distortion or any other anomalies.",
    "result": "pending",
    "workHrs": 4.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "Reli",
    "code": "TCT_001",
    "testCase": "Stress testing under scheduled temperature and humidity settings.",
    "testProcedure": "1. Boot system into Windows OS.\n2. Execute BurnInTest on CPU (100%), Memory(90%) & Disk(90%) and Graphic related test item with 50% load.\n3. Execute HWINFO64 to log temperature of CPU, memory and Disk.\n4. Keep running BurnInTest 27 hour.\nNOTE: Store log file in the directory of saved test report.",
    "testCriteria": "1. System should not hang and has BSOD.\n2. Recorded average temperature of CPU is under 95°C.\n3. Recorded average temperature of Memory is under 85°C or under 95°C (WT Memory).\n4. Record average temperature of Disk is under 70°C or under 85°C (WT Disk).",
    "result": "pending",
    "workHrs": 27.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "Stab",
    "code": "MPT_001",
    "testCase": "To read/write pattern from/to memory for confiming memory's functionality.",
    "testProcedure": "1. Prepare a bootable USB disk including MemTest86/MemTest86+ program.\n2. Configure USB as the first boot device.\n3. Power on system, boot into USB disk, then execute MemTest86/MemTest86+.\n4. Continue executing MemTest86/MemTest86+ testing 2 cycles.",
    "testCriteria": "System should be alive and MemTest86/MemTest86+ shows no error found.",
    "result": "pending",
    "workHrs": 4.0,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "Stab",
    "code": "POR_001",
    "testCase": "Repeatable testing on system ON/OFF from G3 to OS to confirm the stability. (AT Mode)",
    "testProcedure": "1. Install PassMark Rebooter tool on Windows OS.\n2. Configures test fixture's power ON/OFF time setting to OFF for 20 sec. and ON for 2 min.\n3. Connects DUT's power to test fixture.\n4. Reset both counter of OS program and test fixture to zero.\n5. Perform power ON/OFF cycling test 200 times.",
    "testCriteria": "1. Counter value recorded by OS program SHOULD equal to 200.\n2. Display should work normally, no garbage, flicker, distortion or any abnormal issue found.\n3. System should not hang or has BSOD.",
    "result": "pending",
    "workHrs": 8.0,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "Stab",
    "code": "POR_002",
    "testCase": "Repeatable testing on system ON/OFF from S5 to OS to confirm the stability. (ATX Mode)",
    "testProcedure": "1. Install PassMark Rebooter tool on Windows OS.\n2. Use relay module and configures test fixture's power ON/OFF time setting to OFF for 2 min. and ON for 1 sec.\n2. Execute system ON/OFF from S5 to OS by setting Rebooter and cycle number equals to 200.\n3. Record with camera for debugging purpose once error happens.",
    "testCriteria": "1. Counter value recorded SHOULD equal to 200.\n2. Display should work normally, no garbage, flicker, distortion or any abnormal issue found.\n3. System should not hang or has BSOD.",
    "result": "pending",
    "workHrs": 7.0,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "Stab",
    "code": "POR_003",
    "testCase": "Repeatable testing on system reboot to OS to confirm the stability.",
    "testProcedure": "1. Install PassMark Rebooter tool on Windows OS.\n2. Execute reboot test 200 times.\n3. Record with camera for debugging purpose once error happens.",
    "testCriteria": "1. Counter value recorded SHOULD equal to 200.\n2. Display should work normally, no garbage, flicker, distortion or any abnormal issue found.\n3. System should not hang or has BSOD.",
    "result": "pending",
    "workHrs": 4.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "Stab",
    "code": "SSC_001",
    "testCase": "Repeatable testing on system resume from S3 to OS.",
    "testProcedure": "1. Boot into BIOS setup utility, then configure sleep state to S3 (Suspend to RAM).\n2. Install PassMark Sleeper tool on Windows OS.\n3. Execute system resume from S3 to OS by configuring sleeper setting.\n4. Continue performing resume test 200 times.",
    "testCriteria": "1. Counter value recorded SHOULD equal to 200.\n2. Display should work normally, no garbage, flicker, distortion or any abnormal issue found.\n3. System should not hang or has BSOD.",
    "result": "pending",
    "workHrs": 4.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "Stab",
    "code": "SSC_002",
    "testCase": "Repeatable testing on system resume from S4 to OS.",
    "testProcedure": "1. Boot into BIOS setup utility, then configure sleep state to S4 (Hibernation).\n2. Install PassMark Sleeper tool on Windows OS.\n3. Execute system resume from S4 to OS by configuring sleeper setting.\n4. Continue performing resume test 200 times.",
    "testCriteria": "1. Counter value recorded SHOULD equal to 200.\n2. Display should work normally, no garbage, flicker, distortion or any abnormal issue found.\n3. System should not hang or has BSOD.",
    "result": "pending",
    "workHrs": 4.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "Stab",
    "code": "PME_001",
    "testCase": "Stress testing on CPU to find if there is any problem with CPU, RAM or parts of motherboard which are the interface between CPU and RAM.",
    "testProcedure": "1. Boot system into Windows OS.\n2. Execute Prime95, Select 'Options', then 'Torture Test'.\n3. Set option, 'Blend' for Torture Test, then start to do Prime95 test.\n4. Execute HWINFO64 to record temperature of CPU, memory and Disk.\n5. Keep running Prime95 24 hours.",
    "testCriteria": "Prime95 didn't find any errors after 24 hours.",
    "result": "pending",
    "workHrs": 24.0,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "PWR",
    "code": "CPA_001",
    "testCase": "To verify whether power adapter works well with system or not.",
    "testProcedure": "1. Connect power adapter's voltage output to system.\n2. Install devices to all supported slots, expansion slots and IO ports.\n3. Power on system.\n4. Boot system into operating system and start to execute BurnInTest with 100% loading on CARCPU, RAM, Disk, GPGPU, 2D Graphics and 3D Graphics for 20 minutes.\nNOTE: if system installed with LCD display, set brightness level to 100%.",
    "testCriteria": "No error found during test.",
    "result": "pending",
    "workHrs": 0.2,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "PWR",
    "code": "PCAS_001",
    "testCase": "To record maximum power consumed during system boots with minimum supported voltage input of system.",
    "testProcedure": "1. Use equipment to provide power to system.\n2. Set output voltage of equipment to supported maximum voltage input of system.\n3. Install devices to all supported slots, expansion slots and IO ports.\n4. Power on system and start to log maximum current equipment outputs.",
    "testCriteria": "",
    "result": "pending",
    "workHrs": 0.2,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "PWR",
    "code": "PCAS_002",
    "testCase": "To record maximum power consumed during system boots with maximum supported voltage input of system.",
    "testProcedure": "1. Connect power adapter's voltage output to system.\n2. Install devices to all supported slots, expansion slots and IO ports.\n3. Power on system.\n4. Boot system into operating system and start to execute BurnInTest with 100% loading on CARCPU, RAM, Disk, GPGPU, 2D Graphics and 3D Graphics for 20 minutes.\nNOTE: if system installed with LCD display, set brightness level to 100%.",
    "testCriteria": "",
    "result": "pending",
    "workHrs": 0.2,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "PWR",
    "code": "PCS_001",
    "testCase": "To record maximum power consumed during system boots with minimum supported voltage input of system.",
    "testProcedure": "1. Use equipment to provide power to system.\n2. Set output voltage of equipment to maximum supported voltage of system.\n3. Install devices to all supported slots, expansion slots and IO ports.\n4. Power on system and start to log maximum current equipment outputs.\n5. Boot system into operating system and start to execute BurnInTest with 100% loading on CARCPU, RAM, Disk, GPGPU, 2D Graphics and 3D Graphics.\n6. After 10 minutes, get the maximum current value.\nNOTE: if system installed with LCD display, set brightness level to 100%.",
    "testCriteria": "",
    "result": "pending",
    "workHrs": 0.2,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "PWR",
    "code": "PCS_002",
    "testCase": "To record maximum power consumed during system boots with maximum supported voltage input of system.",
    "testProcedure": "1. Use equipment to provide power to system.\n2. Set output voltage of equipment to supported voltage of system.\n3. Install devices to all supported slots, expansion slots and IO ports.\n4. Power on system and start to log maximum current equipment outputs.\n5. Boot system into operating system and start to execute BurnInTest with 100% loading on CARCPU, RAM, Disk, GPGPU, 2D Graphics and 3D Graphics.\n6. After 10 minutes, get the average current value.\nNOTE: if system installed with LCD display, set brightness level to 100%.",
    "testCriteria": "",
    "result": "pending",
    "workHrs": 0.2,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "PWR",
    "code": "PCS_003",
    "testCase": "To record averaged power consumed during system operates.",
    "testProcedure": "1. Use equipment to provide power to system.\n2. Set output voltage of equipment to supported voltage of system.\n3. Install devices to all supported slots, expansion slots and IO ports.\n4. Power on boot system into operating system and put system into S3 mode.\n5. Start to log current equipment outputs.\n6. After 10 minutes, get the average current value.",
    "testCriteria": "",
    "result": "pending",
    "workHrs": 0.2,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "PWR",
    "code": "PCS_004",
    "testCase": "To record averaged power consumed during system is at S3 mode.",
    "testProcedure": "1. Use equipment to provide power to system.\n2. Set output voltage of equipment to supported voltage of system.\n3. Install devices to all supported slots, expansion slots and IO ports.\n4. Power on boot system into operating system and put system into S4 mode.\n5. Start to log current equipment outputs.\n6. After 10 minutes, get the average current value.",
    "testCriteria": "",
    "result": "pending",
    "workHrs": 0.2,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "PWR",
    "code": "PCS_005",
    "testCase": "To record averaged power consumed during system is at S4 mode.",
    "testProcedure": "1. Use equipment to provide power to system.\n2. Set output voltage of equipment to supported voltage of system.\n3. Install devices to all supported slots, expansion slots and IO ports.\n4. Power on boot system into operating system and put system into S5 mode.\n5. Start to log current equipment outputs.\n6. After 10 minutes, get the average current value.",
    "testCriteria": "",
    "result": "pending",
    "workHrs": 0.2,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "PWR",
    "code": "PCS_006",
    "testCase": "To record averaged power consumed during system is at S5 mode.",
    "testProcedure": "1. Use equipment to provide power to system.\n2. Set output voltage of equipment to supported minimum voltage input of system.\n3. Install devices to all supported slots, expansion slots and IO ports.\n4. Power on system and start to log maximum current equipment outputs.",
    "testCriteria": "",
    "result": "pending",
    "workHrs": 0.2,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "Thrm",
    "code": "IRI_001",
    "testCase": "To check heat on surface of system with IR imaging when system operates at 100% loading.",
    "testProcedure": "1. Prepare thermal imaging camera facing to surface of system.\n2. Prepare maximum supported performance of devices for system configuration.\n3. Install all devices mentioned in item 2 into system.\n4. Power on system and boot into Windows OS.\n5. Execute PassMark BurnInTest for 30 minutes.\n6. Record thermal profile and get maximum hot-spots.",
    "testCriteria": "The maximum hot spots should not over requirement.",
    "result": "pending",
    "workHrs": 0.6,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "ESD",
    "code": "AED_001",
    "testCase": "To perform ±8kV air discharge to EUT.",
    "testProcedure": "1. Prepare blue sticker to label the air discharge points.\n2. Use ESD gun to point to the position that selected as air discharge point, not touch the point.\n3. Perform at least 10 discharges at each point.",
    "testCriteria": "EUT should not be influenced and no damage of any component after test.",
    "result": "pending",
    "workHrs": 5.0,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "ESD",
    "code": "AED_002",
    "testCase": "To perform ±15kV air discharge to EUT.",
    "testProcedure": "1. Prepare blue sticker to label the air discharge points.\n2. Use ESD gun to point to the position that selected as air discharge point, not touch the point.\n3. Perform at least 10 discharges at each point.",
    "testCriteria": "EUT should not be influenced and no damage of any component after test.",
    "result": "pending",
    "workHrs": 5.0,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "ESD",
    "code": "CED_001",
    "testCase": "To perform ±4kV contact discharge to EUT.",
    "testProcedure": "1. Prepare yellow sticker to label the contact discharge points.\n2. Use ESD gun to touch labeled point.\n3. Perform at least 10 discharges at each point.",
    "testCriteria": "EUT should not be influenced and no damage of any component after test.",
    "result": "pending",
    "workHrs": 5.0,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "ESD",
    "code": "CED_002",
    "testCase": "To perform ±8kV contact discharge to EUT.",
    "testProcedure": "1. Prepare yellow sticker to label the contact discharge points.\n2. Use ESD gun to touch labeled point.\n3. Perform at least 10 discharges at each point.",
    "testCriteria": "EUT should not be influenced and no damage of any component after test.",
    "result": "pending",
    "workHrs": 5.0,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "ESD",
    "code": "CED_003",
    "testCase": "To perform ±10kV contact discharge to EUT.",
    "testProcedure": "1. Prepare yellow sticker to label the contact discharge points.\n2. Use ESD gun to touch labeled point.\n3. Perform at least 10 discharges at each point.",
    "testCriteria": "EUT should not be influenced and no damage of any component after test.",
    "result": "pending",
    "workHrs": 5.0,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "MEP",
    "code": "Dro_001",
    "testCase": "To verify that system in package will not be destroyed after drop test.",
    "testProcedure": "The tests are performed by an external third-party laboratory and result is gotten from the report.",
    "testCriteria": "",
    "result": "pending",
    "workHrs": 0.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "MEP",
    "code": "IP6X_001",
    "testCase": "To measure air leakage under IP65 standard.",
    "testProcedure": "1. Connect air leakage detection equipment to system.\n2. Fill 6KPa (0.006MPa) air pressure into system.\n3. After 1 minutes, measure system's air pressure. Fill measured air pressure in Remark.",
    "testCriteria": "The measured air pressure should not be lower than 4KPa (0.004MPa)",
    "result": "pending",
    "workHrs": 0.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "MEP",
    "code": "IP6X_002",
    "testCase": "To measure air leakage under IP67 standard.",
    "testProcedure": "1. Connect air leakage detection equipment to system.\n2. Fill 11KPa (0.011MPa) air pressure into system.\n3. After 1 minutes, measure system's air pressure. Fill measured air pressure in Remark.",
    "testCriteria": "The measured air pressure should not be lower than 11KPa (0.011MPa)",
    "result": "pending",
    "workHrs": 0.5,
    "remark": "",
    "isPlanned": true
  },
  {
    "category": "MEP",
    "code": "Vib_001",
    "testCase": "To verify that system will work fine after shock and vibration test.",
    "testProcedure": "The tests are performed by an external third-party laboratory and result is gotten from the report.",
    "testCriteria": "",
    "result": "pending",
    "workHrs": 0.5,
    "remark": "",
    "isPlanned": true
  }
];
